### ISSUE TITLE
When remote host closes connection - ASP.NET process is terminated

### ISSUE THREAD

**Issue by akuryan** [kamsar/Kamsar.WebConsole#2]
When doing a Unicorn sync - we are seeing this error at WebConsole, which kills our application.
Is it possible to avoid terminating ASP.NET process in this case?
```
ERROR Unhandled exception detected. The ASP.NET worker process will be terminated. 
Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: System.Web
   at System.Web.HttpWriter.BufferData(Byte[] data, Int32 offset, Int32 size, Boolean needToCopyData)
   at System.Web.HttpWriter.FlushCharBuffer(Boolean flushEncoder)
   at System.Web.HttpWriter.GetBufferedLength()
   at System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders)
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.Write(String s)
   at System.Web.HttpResponseWrapper.Write(String s)
   at Kamsar.WebConsole.TextWebConsole.Write(String statusMessage, MessageType type, Object[] formatParameters)
   at Kamsar.WebConsole.WebConsole.<.ctor>b__8_0(Object arg)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

**Comment by akuryan** [comment]
Would be hidden when https://github.com/SitecoreUnicorn/Unicorn/pull/390 merged - so, I would close this issue
